# Generated by Django 5.2.7 on 2025-10-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('handle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('online_store_url', models.URLField(blank=True, null=True)),
                ('online_store_preview_url', models.URLField(blank=True, null=True)),
                ('seo', models.JSONField(blank=True, default=dict, null=True)),
                ('metafields', models.JSONField(blank=True, default=list, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('variants', models.JSONField(blank=True, default=list, null=True)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('internal_links', models.JSONField(blank=True, default=list, null=True)),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('seo_issues', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
