# Generated by Django 5.2.7 on 2025-10-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='issues_and_proposed_solutions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
