# Generated by Django 5.2.7 on 2025-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0002_product_issues_and_proposed_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
