# Generated by Django 5.2.7 on 2025-10-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0004_alter_product_created_at_alter_product_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Query_Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('position', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
