# Generated by Django 5.2.7 on 2025-10-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0005_page_query_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(blank=True, null=True)),
                ('indexstatusresult_verdict', models.TextField(blank=True, null=True)),
                ('coverage_state', models.TextField(blank=True, null=True)),
                ('robotsTxtState', models.TextField(blank=True, null=True)),
                ('indexingState', models.TextField(blank=True, null=True)),
                ('pageFetchState', models.TextField(blank=True, null=True)),
                ('crawledAs', models.TextField(blank=True, null=True)),
                ('mobileUsabilityResult', models.TextField(blank=True, null=True)),
                ('referringUrls', models.JSONField(blank=True, default=list, null=True)),
                ('lastCrawlTime', models.CharField(blank=True, max_length=255, null=True)),
                ('googleCanonical', models.TextField(blank=True, null=True)),
                ('userCanonical', models.TextField(blank=True, null=True)),
                ('lcp', models.FloatField(blank=True, null=True)),
                ('cls', models.FloatField(blank=True, null=True)),
                ('inp', models.FloatField(blank=True, null=True)),
                ('pagespeedscore', models.FloatField(blank=True, null=True)),
                ('richResultsResult', models.JSONField(blank=True, default=dict, null=True)),
                ('issues', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
