# Generated by Django 5.2.7 on 2025-10-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_manager', '0006_website_issues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website_issues',
            options={'managed': False},
        ),
    ]
